#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Base44 / Flashback — AI Schema

Single source of truth for all AI/analytics-facing data structures.

These TypedDicts define the shape of:
- Signals
- Orders
- Executions
- Positions
- Trade summaries
- Regime snapshots

All logging / DB writing for AI should conform to this schema.
"""

from __future__ import annotations

import enum
from typing import TypedDict, Literal, Optional, List, Dict, Any


# ---------- Enums / literals ----------

class OwnerType(str, enum.Enum):
    MAIN_TEACHER = "MAIN_TEACHER"          # Manual trades from main account (teacher mode)
    AUTO_STRATEGY = "AUTO_STRATEGY"        # Any fully automated strategy
    SEMI_AUTO = "SEMI_AUTO"                # You approve, bot executes
    COPIER = "COPIER"                      # Cloned trades on subaccounts
    OTHER = "OTHER"                        # Fallback / legacy


class TradeOutcome(str, enum.Enum):
    WIN = "WIN"
    LOSS = "LOSS"
    BREAKEVEN = "BREAKEVEN"
    UNKNOWN = "UNKNOWN"                    # If not yet closed / computed


SideLiteral = Literal["LONG", "SHORT"]
ExitReasonLiteral = Literal[
    "TP",
    "SL",
    "MANUAL_CLOSE",
    "TIME_EXIT",
    "BREAKER_CLOSE",
    "OTHER",
]


# ---------- Core entities ----------

class SignalLog(TypedDict, total=False):
    """
    One signal generated by a scanner / strategy.

    Required:
      - signal_id: unique ID (str)
      - ts_ms: timestamp in epoch ms
      - symbol: e.g. "BTCUSDT"
      - timeframe: e.g. "5m", "15m"
      - side: "LONG" or "SHORT"
      - source: which module/engine emitted this (e.g. "signal_engine_v1")

    Optional (but highly recommended):
      - confidence: 0.0 - 1.0
      - stop_hint_price: suggested stop price (float)
      - owner: who conceptually owns this signal (MAIN_TEACHER / AUTO_STRATEGY / etc.)
      - sub_uid: target subaccount UID (if known at signal time)
      - strategy_role: logical role (e.g. "TREND_SYSTEM", "BREAKOUT", "CANARY")
      - regime_tags: list of short tags: ["trend_up", "high_vol", "session_London"]
      - extra: free-form dict for versioned experiments
    """
    signal_id: str
    ts_ms: int
    symbol: str
    timeframe: str
    side: SideLiteral
    source: str

    confidence: Optional[float]
    stop_hint_price: Optional[float]

    owner: Optional[str]
    sub_uid: Optional[str]
    strategy_role: Optional[str]
    regime_tags: List[str]
    extra: Dict[str, Any]


class OrderLog(TypedDict, total=False):
    """
    One order created in response to a signal.

    Required:
      - order_id: exchange order ID or internal ID
      - ts_ms: creation timestamp
      - symbol
      - side
      - order_type: "LIMIT", "MARKET", "STOP", etc.
      - qty: order size in contracts
      - price: limit/trigger price (if applicable)

    Optional:
      - signal_id: link back to SignalLog
      - sub_uid: which subaccount placed it
      - owner: owner type
      - strategy_role: which strategy profile
      - exit_profile: e.g. "STANDARD_5TP", "SCALP", "SWING"
      - reduce_only: bool
      - post_only: bool
      - extra: free-form
    """
    order_id: str
    ts_ms: int
    symbol: str
    side: SideLiteral
    order_type: str
    qty: float
    price: float

    signal_id: Optional[str]
    sub_uid: Optional[str]
    owner: Optional[str]
    strategy_role: Optional[str]
    exit_profile: Optional[str]

    reduce_only: Optional[bool]
    post_only: Optional[bool]

    extra: Dict[str, Any]


class ExecutionLog(TypedDict, total=False):
    """
    One execution/fill event.

    Required:
      - exec_id
      - order_id
      - ts_ms
      - symbol
      - side
      - qty
      - price

    Optional:
      - fee: trading fee paid for this fill
      - pnl_increment: realized PnL contributed by this exec (if known)
      - sub_uid, owner, strategy_role
      - latency_ms: from signal to first fill or from order create to fill
      - extra
    """
    exec_id: str
    order_id: str
    ts_ms: int
    symbol: str
    side: SideLiteral
    qty: float
    price: float

    fee: Optional[float]
    pnl_increment: Optional[float]

    sub_uid: Optional[str]
    owner: Optional[str]
    strategy_role: Optional[str]

    latency_ms: Optional[int]
    extra: Dict[str, Any]


class PositionSnapshot(TypedDict, total=False):
    """
    Snapshot of a position at a given moment.

    Required:
      - ts_ms
      - sub_uid
      - symbol
      - size: signed size (positive = long, negative = short)
      - avg_entry: average entry price

    Optional:
      - unrealized_pnl
      - max_favorable_excursion: best open PnL so far (in R or USD)
      - max_adverse_excursion: worst open PnL so far
      - owner, strategy_role
      - extra
    """
    ts_ms: int
    sub_uid: str
    symbol: str
    size: float
    avg_entry: float

    unrealized_pnl: Optional[float]
    max_favorable_excursion: Optional[float]
    max_adverse_excursion: Optional[float]

    owner: Optional[str]
    strategy_role: Optional[str]

    extra: Dict[str, Any]


class TradeSummaryLog(TypedDict, total=False):
    """
    Summary of a fully closed trade (from flat → flat).

    Required:
      - trade_id: internal ID for the round-trip
      - sub_uid
      - symbol
      - side: initial direction (LONG/SHORT)
      - opened_ts_ms
      - closed_ts_ms
      - outcome: WIN/LOSS/BREAKEVEN/UNKNOWN
      - r_multiple: realized R multiple
      - realized_pnl: in USD (or quote currency)

    Optional:
      - signal_id: main signal that started it
      - owner, strategy_role
      - entry_price, exit_price
      - max_favorable_excursion_r
      - max_adverse_excursion_r
      - holding_ms
      - exit_reason: TP/SL/etc.
      - regime_at_entry: short tag string or JSONified snapshot
      - regime_at_exit
      - extra
    """
    trade_id: str
    sub_uid: str
    symbol: str
    side: SideLiteral

    opened_ts_ms: int
    closed_ts_ms: int

    outcome: str  # use TradeOutcome values
    r_multiple: float
    realized_pnl: float

    signal_id: Optional[str]
    owner: Optional[str]
    strategy_role: Optional[str]

    entry_price: Optional[float]
    exit_price: Optional[float]

    max_favorable_excursion_r: Optional[float]
    max_adverse_excursion_r: Optional[float]

    holding_ms: Optional[int]
    exit_reason: Optional[ExitReasonLiteral]

    regime_at_entry: Optional[str]
    regime_at_exit: Optional[str]

    extra: Dict[str, Any]


class RegimeSnapshotLog(TypedDict, total=False):
    """
    Snapshot of market regime used at signal/trade time.

    Can be stored separately or embedded as JSON string in other records.

    Fields are intentionally generic and can evolve:
      - ts_ms
      - symbol
      - timeframe
      - adx
      - atr_pct: ATR / price * 100
      - vol_zscore: volume z-score vs lookback
      - trend_state: e.g. "up", "down", "range"
      - session: e.g. "Asia", "London", "NY"
      - tags: list of regime tags
      - extra
    """
    ts_ms: int
    symbol: str
    timeframe: str

    adx: Optional[float]
    atr_pct: Optional[float]
    vol_zscore: Optional[float]

    trend_state: Optional[str]
    session: Optional[str]
    tags: List[str]

    extra: Dict[str, Any]
